<a href="https://colab.research.google.com/github/GokhanAsilturk/Colab-Python-Projects/blob/colabworks/Asilturk_AC205_%D0%9F%D1%80%D0%B0%D0%BA_%D1%80%D0%BE%D0%B1_2%D1%87%D0%B0%D1%81%D1%82_2_%D0%90%D0%BD%D0%B0%D0%BB%D1%96%D0%B7_%D0%B4%D0%B0%D0%BD%D0%B8%D1%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Практична робота 2, частина 2.** 

---


**Підготовлено:** Гьокхан Асільтюрк

**Група:** АС-205

**Номер:** 3

##Завдання 1. Аналіз клієнтів оператора мобільного зв'язку



Задати рядок, що містить імена клієнтів, наприклад:
C_names = “Barnes Abramson Macduff Johnson Andrews Lewin Brown”
І інформація про тривалість дзвінків клієнтів у роумінгу за кожен останніх 6 місяців
(варіюється від 100 до 350 хв./міс).
1. Згенерувати NumPy масив (Customer's roaming call duration), що містить цю інформацію,
використовуючи відповідний метод модуля random.
2. Вибрати з нього всі рядки, що містять інформацію про клієнтів Abramson і Johnson.
3. Вибрати інформацію про всіх клієнтів, крім Macduff та Lewin.
4. Вивести інформацію про клієнта Brown за період 2-4 місяці
5. Вивести інформацію про всіх клієнтів, крім Barnes за непарні місяці.
6. Вартість хвилини розмови в роумінгу складає 1.6 $. Створіть новий масив NumPy (Customer's
roaming call cost), що містить інформацію про витрати кожного клієнта в певний місяць (на
основі даних з масиву “Customer's roaming call duration”).
7. Курс долара становить 28₴. Розрахуйте та виведіть загальні витрати клієнта Andrews у
гривнях.

У завданнях 2,3, 4, 6, 7 задати свої імена відповідно до створеного рядка та вартість роумінгу.

In [ ]:
import numpy as np

c_names = "Barnes Abramson Macduff Johnson Andrews Lewin Brown"

customers_total_statistics = {}
customers_logs = {}

customers_total_amount = {}
customers_monthly_amount = {}


def show_total_statistics(month):
    print("\tStatistics for %d months:\n\n" % month)
    splitted_names = c_names.split()

    for name in splitted_names:
        # find_customers_statistics(name,month)
        find_customers_statistics(name, month)
    for customer, total in customers_total_statistics.items():
        print("customer: %s\nStatistic for %d months: %d minutes\n" % (customer, month, total))


def find_customers_statistics(customer_name, month):
    phoneCall_statistic = np.random.randint(100, 350, size=month)
    customers_logs.setdefault(customer_name, phoneCall_statistic)
    total_statistic = sum(phoneCall_statistic)  # istatistiklerin toplamını alıyoruz
    customers_total_statistics.setdefault(customer_name, total_statistic)


def calculate_amount(dollar_price, course):
    current_price = dollar_price * course

    for name, logArray in customers_logs.items():
        amountList = []
        for log in logArray:
            amountList.append(int(current_price) * int(log))

        amountList_numpy = np.array(amountList)
        customers_monthly_amount.setdefault(name, amountList_numpy)
        total_amount = sum(amountList_numpy)
        customers_total_amount.setdefault(name, total_amount)


# -------------------2-------------------

def info_selected_customer(customer_name):
    customer_name = customer_name.title()

    print("\n\n\n-------------------------------\n\n\ncustomer: %s" % customer_name)

    if customer_name in customers_total_statistics:
        print("\ncustomer logs monthly:")
        i = 1
        for log in customers_logs[customer_name]:
            if i < (len(customers_logs[customer_name]) / 2):
                print(" " + str(i) + " month: %s minutes" % str(log), end=" ")
                i = i + 1
            elif i == (len(customers_logs[customer_name]) / 2):
                print(" " + str(i) + " month: %s minutes" % str(log))
                i = i + 1
            else:
                print(" " + str(i) + " month: %s minutes" % str(log), end=" ")
                i = i + 1
        

        print("\nTotal statistic: %d minutes" % (customers_total_statistics[customer_name]))

    if customer_name in customers_monthly_amount:
        print("\ncustomer monthly amount:")
        i = 1
        for amount in customers_monthly_amount[customer_name]:
            if i < (len(customers_monthly_amount[customer_name]) / 2):
                print(" " + str(i) + " month: %s UAH" % str(amount), end=" ")
                i = i + 1
            elif i == (len(customers_monthly_amount[customer_name]) / 2):
                print(" " + str(i) + " month: %s UAH" % str(amount))
                i = i + 1
            else:
                print(" " + str(i) + " month: %s UAH" % str(amount), end=" ")
                i = i + 1

        print("\nTotal amount: %d UAH / %d$" % (
            customers_total_amount[customer_name], customers_total_amount[customer_name] / float(1.6)))


# -------------------3-------------------


def get_input_for_filter():
    name_list = []
    for number in range(2):
        name_of_customer = input("Enter customer %d: " % (number + 1))
        name_list.append(name_of_customer.title())
    print("\n\n")
    info_without_unselected_customers(name_list)


def info_without_unselected_customers(name_list):
    check = (numpy_customer_names != str(name_list[0])) & (
            numpy_customer_names != str(name_list[1]))  # true false bilgisi alıyoruz

    new_customer_names = numpy_customer_names[check]
    new_customer_logs = numpy_customer_logs[check]
    new_customer_total_logs = numpy_customer_total_logs[check]
    new_customer_monthly_amount = numpy_customer_monthly_amount[check]
    new_customer_total_amount = numpy_customer_total_amount[check]

    for index in range(len(new_customer_names)):
        print("Name: ", new_customer_names[index])

        print("Monthly logs: ", end="")
        for i in range(len(new_customer_logs)):
            if i == len(new_customer_logs) - 1:
                print(str(new_customer_logs[index][i]), "min")
            else:
                print(str(new_customer_logs[index][i]), "min", end=" ")

        print("Total log: ", new_customer_total_logs[index], " minutes")

        print("Monthly amount: ", end="")
        for i in range(len(new_customer_logs)):
            if i == len(new_customer_monthly_amount) - 1:
                print(str(new_customer_monthly_amount[index][i]), "UAH")
            else:
                print(str(new_customer_monthly_amount[index][i]), "UAH", end=" ")

        print("Total amount: ", new_customer_total_amount[index], "UAH\n")


# -------------------4-------------------

def info_for_2_4_months(customer_name):
    customer_name = customer_name.title()

    customer_index = list(numpy_customer_names).index(customer_name)
    customer_log = numpy_customer_logs[customer_index]
    customer_monthly_amount = numpy_customer_monthly_amount[customer_index]

    print("Name: %s" % customer_name)
    print("customer monthly logs: ")
    new_log_list = []
    total_amount = 0
    for i in range(2, 5):
        new_log_list.append(customer_log[i + 1])
        print("%d month: %d min = %d UAH / %d$" % (
            i, customer_log[i + 1], customer_monthly_amount[i + 1], customer_monthly_amount[i + 1] / 1.6))
        total_amount = total_amount + customer_monthly_amount[i + 1]

    print("Total log for 2-4 months: ", sum(new_log_list), "minutes")
    print("Total amount for 2-4 months: %d UAH / %d$" % (total_amount, total_amount / 1.6))


# -------------------5-------------------


def info_for_1_month_without_1_person(customer_name):
    customer_name = customer_name.title()
    check = (numpy_customer_names != customer_name)

    new_customer_names = numpy_customer_names[check]
    new_customer_logs = numpy_customer_logs[check]
    new_customer_total_logs = numpy_customer_total_logs[check]
    new_customer_monthly_amount = numpy_customer_monthly_amount[check]
    new_customer_total_amount = numpy_customer_total_amount[check]

    for index in range(len(new_customer_names)):
        print("Name: ", new_customer_names[index])

        print("Monthly logs: ", end="")
        for i in range(len(new_customer_logs)):
            if i == len(new_customer_logs) - 1:
                print(str(new_customer_logs[index][i]), "min")
            else:
                print(str(new_customer_logs[index][i]), "min", end=" ")

        print("Total log: ", new_customer_total_logs[index], " minutes")

        print("Monthly amount: ", end="")
        for i in range(len(new_customer_logs)):
            if i == len(new_customer_monthly_amount) - 1:
                print(str(new_customer_monthly_amount[index][i]), "UAH")
            else:
                print(str(new_customer_monthly_amount[index][i]), "UAH", end=" ")

        print("Total amount: %dUAH / %d$" % (
            new_customer_total_amount[index], int(new_customer_total_amount[index] / 1.6)) + "\n")


# -------------------6-------------------
def calculate_dollar(price):
    monthly_amounts = []

    for logs in numpy_customer_logs:
        temp_monthly_amount = []
        for log in logs:
            temp_monthly_amount.append(int(log * price))
        monthly_amounts.append(temp_monthly_amount)

    numpy_monthly_amount = np.array(list(monthly_amounts))
    numpy_random_month = np.random.randint(0, len(numpy_monthly_amount) - 1, size=len(numpy_customer_names))
    for name in numpy_customer_names:
        amounts = numpy_monthly_amount[np.where(numpy_customer_names == name)]
        random_month_index = numpy_random_month[np.where(numpy_customer_names == name)]
        print("\ncustomer Name: ", name)
        print("Amount for %s month: " % int(random_month_index + 1), int(amounts[0][random_month_index]), "$")

    dollar_amounts.append(numpy_monthly_amount)


# ------------------7-------------------

def calculate_grn(customer_name, price):
    customer_dollar_amount_list = dollar_amounts[0][np.where(numpy_customer_names == customer_name)]
    total_amount = sum(customer_dollar_amount_list[0]) * price
    print("customer Name: %s" % customer_name.title())
    for dollar_amount in customer_dollar_amount_list[0]:
        print(
            "%d month: %d UAH" % (list(customer_dollar_amount_list[0]).index(dollar_amount) + 1, dollar_amount * price))
    print("Total amount: %d UAH" % total_amount)


# --------------------------------main------------------------------------------
print("\n\n---------------1----------------\n")
show_total_statistics(6)
calculate_amount(float(1.6), int(28))
print("\n")

numpy_customer_names = np.array(list(customers_total_statistics.keys()))
numpy_customer_logs = np.array(list(customers_logs.values()))
numpy_customer_total_logs = np.array(list(customers_total_statistics.values()))
numpy_customer_monthly_amount = np.array(list(customers_monthly_amount.values()))
numpy_customer_total_amount = np.array(list(customers_total_amount.values()))
# -------------------2-------------------
print("\n\n---------------2----------------\n")
info_selected_customer("Abramson")
info_selected_customer("johnson")

# ------------------3-------------------
print("\n\n---------------3----------------\n")
get_input_for_filter()


# ------------------4-------------------
print("\n\n---------------4----------------\n")
info_for_2_4_months('brown')

# ------------------5-------------------
print("\n\n---------------5----------------\n")
info_for_1_month_without_1_person('barnes')

# ------------------6-------------------
print("\n\n---------------6----------------\n")
dollar_amounts = []
calculate_dollar(1.6)

# ------------------7-------------------
print("\n\n---------------7----------------\n")
calculate_grn('Andrews', 28)




---------------1----------------

	Statistics for 6 months:


customer: Barnes
Statistic for 6 months: 1610 minutes

customer: Abramson
Statistic for 6 months: 1411 minutes

customer: Macduff
Statistic for 6 months: 1205 minutes

customer: Johnson
Statistic for 6 months: 1453 minutes

customer: Andrews
Statistic for 6 months: 1371 minutes

customer: Lewin
Statistic for 6 months: 1525 minutes

customer: Brown
Statistic for 6 months: 1265 minutes





---------------2----------------




-------------------------------


customer: Abramson

customer logs monthly:
 1 month: 151 minutes  2 month: 326 minutes  3 month: 322 minutes
 4 month: 134 minutes  5 month: 201 minutes  6 month: 277 minutes 
Total statistic: 1411 minutes

customer monthly amount:
 1 month: 6644 UAH  2 month: 14344 UAH  3 month: 14168 UAH
 4 month: 5896 UAH  5 month: 8844 UAH  6 month: 12188 UAH 
Total amount: 62084 UAH / 38802$



-------------------------------


customer: Johnson

customer logs monthly:
 1 month: 1

## Завдання 2. Робота з модулем random, fancy indexing

Тривалість розмов клієнтів мобільного оператора в роумінгу за останні M місяців варіюється від 1000 до 4000 хвилин.
Припустимо, у компанії обслуговується лише N абонентів.
Згенерувати NumPy, що містить інформацію про “Roaming call duration”, використовуючи відповідний метод модуля random.
Використовуючи Fancy indexing вибрати підмножину у вказаному порядку, представленому двома 2 NumPy масивами:

i=[[2,4],[7,8]], 

j=[[0,2],[9,6]]

Варіант: 3

N=31 M=62

In [ ]:
import numpy as np


def create_random_logs(month,number_of_customers):
  
  customers_call_duration = np.random.randint(1000,4001, [number_of_customers, month])
  
  i = np.array([2, 4, 7, 8]).reshape(2,2)
  j = np.array([0, 2, 9, 6]).reshape(2,2)

  print(customers_call_duration, customers_call_duration[i , j] , sep='\n\n')



create_random_logs(62,31)





[[1397 2396 1012 ... 1253 2016 1961]
 [3791 1354 2687 ... 3269 1960 3801]
 [1242 2346 1215 ... 2916 1121 1956]
 ...
 [3912 3017 1547 ... 1285 2312 2063]
 [3355 2524 3428 ... 1566 1070 1266]
 [3344 1485 3410 ... 3613 2949 2391]]

[[1242 3278]
 [1171 1830]]
