<a href="https://colab.research.google.com/github/GokhanAsilturk/Colab-Python-Projects/blob/colabworks/%D0%92%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_NumPy_Asilturk_AC205.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практична робота 2. Ч. 1. Вступ до NumPy
---
Підготовлено: Гьокхан Асільтюрк

Група: АС-205

Номер: 3

## 1. Створити вектор нульових значень (довжиною a)

In [ ]:
import numpy as np
a=5

print(np.zeros((a), np.dtype(int)))

[0 0 0 0 0]


## 2. Створити вектор нульових значень (довжиною b), змінити (b-4) елемент на значення с.

In [ ]:
import numpy as np

b=10
c=0

array = np.arange(10)

array[b-4] = c

print(array)



[0 1 2 3 4 5 0 7 8 9]


## 3. Створити вектор із значеннями в діапазоні від n до m

In [ ]:
import numpy as np

n=2
m=10

array = np.arange(n+1,m,1)



print(array)

[3 4 5 6 7 8 9]


## 4. Розгорнути вектор (перший елемент стає останнім)

In [ ]:
import numpy as np

numpy_array = np.array([1,2,3,4,5,6,7,8,9,10])

print(numpy_array[::-1])

[10  9  8  7  6  5  4  3  2  1]


## 5. Зі списку L=[0,1,2,3,4,5,6,7,8] створити матрицю 3х3.

In [ ]:
import numpy as np

lst = [0,1,2,3,4,5,6,7,8]

numpy_lst = np.array(lst)

numpy_lst.reshape(3,3)

print(array)


[1 2 3 4 5 6]


## 6. Створити матрицю 2×3 зі значеннями в діапазоні від 0 до 5

In [ ]:
import numpy as np

numpy_array = np.arange(6)

array_2x3 = numpy_array.reshape(2,3)

print(array_2x3)

[[0 1 2]
 [3 4 5]]


## 7. Створити матрицю a x b з 5 всередині та 1 на межах

In [ ]:
import numpy as np

array = np.arange(1,7,1)
array.reshape(3,2)
print(array)


[1 2 3 4 5 6]


## 8. (Exercise) Сформувати зрізи для отримання зафарбованих елементів.

In [ ]:
import numpy as np
matrixzeros = np.zeros((4,4), np.dtype(int))
matrixones_vertical = np.ones((6,1),np.dtype(int))
matrixones_horizontal = np.ones((1,4),np.dtype(int))

matrix = np.concatenate([matrixones_horizontal,matrixzeros], axis=0)
matrix = np.concatenate([matrix,matrixones_horizontal], axis=0)

matrix = np.concatenate([matrixones_vertical,matrix], axis=1)
matrix = np.concatenate([matrix,matrixones_vertical], axis=1)

print(matrix)
print("\n")

first_row = matrix[0]
last_row = matrix[-1]

first_column = matrix[:,0]
last_column = matrix[:,-1]




print("first row: "+str(first_row),"\nLast row: "+str(last_row))
print("\n")
print("First column: " + str(first_column),"\nLast_column: " +str(last_column) + "\n")


deleted_matrix = np.delete(matrix,0,0)
deleted_matrix = np.delete(deleted_matrix,-1,0)
deleted_matrix = np.delete(deleted_matrix,0,1)
deleted_matrix = np.delete(deleted_matrix,-1,1)

print(deleted_matrix)



[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


first row: [1 1 1 1 1 1] 
Last row: [1 1 1 1 1 1]


First column: [1 1 1 1 1 1] 
Last_column: [1 1 1 1 1 1]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


## 8. Сформувати зрізи для отримання зафарбованих елементів.

In [ ]:
import numpy as np

numpy_array = np.array([2,3,6,8,11,34])
numpy_matrix = np.array([2,3,6,8,11,34,11,22,3,67,11,87,3,6,3,11,89,14,4,5,8,1,4,67])
numpy_matrix = numpy_matrix.reshape(4,6)
selected_items = []

print(str(numpy_array)+"\n")
print(str(numpy_matrix)+"\n")
print("_______________________\n 1:")

#1
for i in range(2,4):
  selected_items.append(numpy_array[i])
print("\n"+str(selected_items)+"\n")
print("_______________________\n 2:")

#2
print(str(numpy_matrix[:,1].reshape(4,1))+"\n")
print(str(numpy_matrix[:,2].reshape(4,1))+"\n")
print("_______________________\n 3:")

#3
print(str(numpy_matrix[:,1].reshape(4,1))+"\n")
print(str(numpy_matrix[:,3].reshape(4,1))+"\n")
print(str(numpy_matrix[:,5].reshape(4,1))+"\n")
print("_______________________\n 4:")

#4
print(str(numpy_matrix[1:5,4].reshape(3,1))+"\n")
print(str(numpy_matrix[1:5,5].reshape(3,1))+"\n")
print("_______________________\n 5:")

#5
print(str(numpy_matrix[0:2]))
print("_______________________\n 6:")

#6
print(str(numpy_matrix[2,0:3]))


[ 2  3  6  8 11 34]

[[ 2  3  6  8 11 34]
 [11 22  3 67 11 87]
 [ 3  6  3 11 89 14]
 [ 4  5  8  1  4 67]]

_______________________
 1:

[6, 8]

_______________________
 2:
[[ 3]
 [22]
 [ 6]
 [ 5]]

[[6]
 [3]
 [3]
 [8]]

_______________________
 3:
[[ 3]
 [22]
 [ 6]
 [ 5]]

[[ 8]
 [67]
 [11]
 [ 1]]

[[34]
 [87]
 [14]
 [67]]

_______________________
 4:


ValueError: ignored