<a href="https://colab.research.google.com/github/GokhanAsilturk/Colab-Python-Projects/blob/colabworks/%D0%9F%D1%80%D0%B0%D0%BA_%D1%80%D0%BE%D0%B1_3_%D0%90%D0%BD%D0%B0%D0%BB%D1%96%D0%B7_%D0%B4%D0%B0%D0%BD%D0%B8%D1%85_Asilturk_AC205.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Практична робота 3**
Аналіз дзвінків клієнтів мобільного оператора у роумінгу

---


**Підготовлено:** Гьокхан Асільтюрк

**Група:** АС-205

**Номер:** 3


##**Опис предметної області:**

Сформувати таблицю – набір даних про довжину дзвінків клієнтів у роумінгу по різним регіонам України (Таблиця 1).

* **Перший регіон** 

  * Для непарних варіантів:

    Рядки – місяці 2021 р. (10 місяців), стовпці – міста регіону (кількість   відповідно варіанту)
 
  * Для парних варіантів:

    Рядки – міста регіону (кількість відповідно варіанту), стовпці-місяці 2021 р.  (10 місяців).

* **Другий регіон**

  * Для непарних варіантів:

    Рядки–міста регіону (кількість відповідно варіанту) * 10, стовпці–місяці 2021 р. (діапазон відповідно варіанту).

 * Для парних варіантів:

    Рядки – місяці 2021 р. (діапазон відповідно варіанту), стовпці-міста регіону (кількість відповідно варіанту)+20


Використовуючи відповідні функції бібліотеки NumPy для зміни форми масивів, їх злиття та розбиття, та також універсальні функції NumPy реалізуватизавдання:

1. Згенерувати два ndarray (матриці) по заданим регіонам, відповідно заданої у описі предметної області структурі та відповідної розмірності. Комірки матриць зберігають тривалості дзвінків абонентів у роумінгу (згенерувати значення в зазначеному діапазоні згідно назвам регіонів в таблиці 2).


2. Створити новий (загальний) ndarray для зберігання всієї інформації з двох заданих регіонів за вказаний в таблиці 3 діапазон місяців, виконавши операції зрізу, трансформації (рядки нової матриці - міста, стовпці - місяці)і операції об'єднання.


На основі нового набору:


3. Розрахувати сумарну, максимальну та мінімальну тривалості дзвінків для кожного місяця і середню кількість дзвінків по кожному місту.


4. Розрахувати загальну (сумарну) тривалість дзвінків за три останніх місяці зазначеного в таблиці 3 діапазону по всьому набору даних.


5. Припустимо, що ви отримали 10 окремих рядків, які зберігають інформацію по 10 новим містам за всі місяці 2020 року і минулі місяці 2021(січень - жовтень) - 22 значення в кожному отриманому рядку.


6. Додайте нову інформацію в набір, вибравши інформацію тільки за ті місяці,які вам
необхідні (таблиця 3)


7. Використовуючи універсальні функції, вивести максимальну та мінімальну
тривалості дзвінків по кожному місту і місяць (визначити назву міста та місяця
за номером), коли вона була отримана.


8. За кожний місяць сформувати твердження: «В середньому в місяці Хтривалість
дзвінків в роумінгу становила Y плюс \ мінус Z хвилин». Y і Z визначити за
допомогою відповідних універсальних функцій. Х - номер місяця (від 1 до 12), а
не номер стовпчика.


9. Для кожного міста та місяця визначити і вивести таке значення тривалості
дзвінків L, що все значення тривалості дзвінків для даного міста (місяця) менше
L з ймовірністю 60%.

**Варіант:**

* Таблиця 1 : 

 * Кількість міст - 11 
 * Диапазон місяців - 2-8 
 * Регіон 1 - Одеса 
 * Регіон 2 - Херсон

* Таблиця 2 : 
  * Діапазон тривалості дзвінка:
    * Одеса  - 100-250
    * Херсон - 90-240

* Таблиця 3: 
 * 6-8


In [ ]:
import numpy as np
#--------------1------------
odessa_months = 10
odessa_cities = 11

kherson_cities = 11*10
kherson_months = 12

odessa_array = np.random.randint(100, 250 , size=[odessa_months, odessa_cities])
kherson_array = np.random.randint(90, 240 , size=[kherson_cities, kherson_months])
print("Odessa:\n", odessa_array, "\n\nKherson:\n", kherson_array)

#--------------2------------
print("\n\nTask 2:")
odessa_kherson_array = np.concatenate((np.transpose(odessa_array[6:8, :]), (kherson_array[:, 6:8])))
print("\n\nConcatenated array:\n",odessa_kherson_array)

#--------------3------------
print("\n\nTask 3:")
min_roaming_duration = np.min(odessa_kherson_array ,axis=0)
max_roaming_duration = np.max(odessa_kherson_array, axis=0)
total_roaming_duration  = np.sum(odessa_kherson_array, axis=0)
average_roaming_duration = np.mean(odessa_kherson_array, axis=1)
print("\nMinimum roaming duration:", min_roaming_duration ,"\nMaximum roaming duration:",max_roaming_duration,"\n\nAverage roaming duration:\n",average_roaming_duration,"\n\nTotal roaming_duration:",total_roaming_duration)

#--------------4------------
print("\nTask 4:")
total_last_3months = np.sum(odessa_kherson_array[6:8, -3:])
print("\nTotal roaming duration for last 3 months: ", total_last_3months)

#--------------5------------
min_value = odessa_kherson_array.min()
max_value = odessa_kherson_array.max()
new_array = np.random.randint(min_value, max_value , size=[10,22])
print("\n\nNew array for task 5:\n",new_array)

#--------------6------------
new_array2 = np.concatenate((odessa_kherson_array, new_array[::,6:8]))
print("\n\nNew array for task 6:\n",new_array2)

#--------------7------------
min_newArray2 = np.min(new_array2, axis=0)
max_newArray2 = np.max(new_array2, axis=0)
print("\n\nMax-Min arrays for task 7:\n\n", "min:\n",np.min(new_array2, axis=0), "\nmax:\n",np.max(new_array2, axis=0), "\nmin:\n",np.min(new_array2, axis=1), "\nmax:\n",np.max(new_array2, axis=1))

months = ['July', 'August']

i=0
for roaming_durations in new_array2:
  min_month_index = np.where(roaming_durations == np.min(roaming_durations,axis=0))
  max_month_index = np.where(roaming_durations == np.max(roaming_durations,axis=0))

  min_roaming_duration = np.min(roaming_durations,axis=0)
  max_roaming_duration = np.max(roaming_durations,axis=0)
  print("In city #",(i+1)," the lowest roaming duration is",min_roaming_duration,"minutes (",str(months[int(min_month_index[0])]),") and the highest roaming duration is",max_roaming_duration,"minutes (",str(months[int(max_month_index[0])]),").")
  i=i+1

#--------------8------------
print("\nTask 8:")
for x in range(new_array2.shape[1]):
  print("\naverage duration of roaming calls of %d months: %d +\- %d" %(x+1, new_array2.mean(axis=0)[x], new_array2.std(axis=0)[x]))

#--------------9------------
print("\n\nResults of task 9:\n")

arr_L = np.percentile(new_array2,60)
print(arr_L,"\n")
arr_L = np.percentile(new_array2, 60, axis=0)
print(arr_L,"\n")
arr_L = np.percentile(new_array2, 60, axis=1)
arr_L,"\n"

Odessa:
 [[139 100 226 143 196 245 135 244 108 132 185]
 [181 115 204 155 194 199 212 115 126 142 141]
 [179 122 187 146 208 129 194 195 196 136 186]
 [124 226 133 189 165 140 104 170 183 129 165]
 [102 111 134 142 217 188 113 163 138 162 207]
 [115 230 123 227 205 242 107 113 185 240 180]
 [139 158 205 174 107 224 208 178 100 247 248]
 [240 156 122 109 200 156 118 144 119 182 240]
 [126 211 169 158 202 186 118 231 171 130 238]
 [230 200 228 216 127 137 155 165 232 133 205]] 

Kherson:
 [[171  96 237 ... 129 229 202]
 [163 182 199 ... 231 118 200]
 [105 148 138 ... 199  95 209]
 ...
 [119 217 203 ... 142 230 213]
 [183 223 111 ... 111 182 131]
 [135 148  92 ... 158 169 142]]


Task 2:


Concatenated array:
 [[139 240]
 [158 156]
 [205 122]
 [174 109]
 [107 200]
 [224 156]
 [208 118]
 [178 144]
 [100 119]
 [247 182]
 [248 240]
 [198 137]
 [136 239]
 [119 123]
 [214  94]
 [190 145]
 [ 98 157]
 [ 91 104]
 [190 101]
 [140 129]
 [194 162]
 [148 157]
 [186 228]
 [125 113]
 [205 127]
 [142 11

(array([199.6, 157.2, 171.8, 148. , 162.8, 196.8, 172. , 164.4, 111.4,
        221. , 244.8, 173.6, 197.8, 121.4, 166. , 172. , 133.4,  98.8,
        154.4, 135.6, 181.2, 153.4, 211.2, 120.2, 173.8, 130.8, 141. ,
        132. , 185.6, 189.4, 197.2, 168. , 176. , 218.2, 107. , 179.2,
        204.4, 229.6, 163.2, 164.8, 122.2, 218.4, 142.8, 183.4, 161.8,
        201.4, 127.6, 200.8, 193. , 146.2, 205.2, 213.6, 173.8, 115.6,
        173.6, 230.4, 149.2, 154.4, 223.6, 172.8, 130. , 201. , 160.2,
        180.4, 134.4, 176.8, 160.6, 188. , 140.6, 186.4, 105. , 191.4,
        188.4, 170.2, 146. , 202.6, 166.8, 148.6, 149.4, 103.2, 187.2,
        170.8, 218.2, 163. , 192.4, 141.6, 145.8, 212.4, 195. , 103.8,
        152.2, 197. , 175.4,  99.8, 123. , 196.8, 183.8, 156.6, 158.8,
        158.2, 158.6, 145. , 154.2, 168.8, 125. , 142.6, 162.8, 146.2,
        149.8, 185. , 178. , 150.8, 171.4, 212.6, 178.4, 116.6, 200.4,
        157. , 183.4, 153.6, 118.2, 174.2, 236.4, 184.2, 128.8, 207.6,
      